name: Quick Tests

on:
  push:
    branches-ignore:
      - master
      - develop
  workflow_run:
    workflows: [ "Ruleset checks" ]
    branches-ignore:
      - master
      - develop

jobs:
  # Performs some quick tests.
  # This is a much quicker test suite which only runs the unit tests and linting
  # against the low/high supported PHP/PHPCS combinations.
  #
  # Performs the following steps:
  # - Checks out the repository.
  # - Configures caching for Composer.
  # - Sets up PHP.
  # - Installs PHPCS.
  # - Install Composer dependencies.
  # - Runs the Composer linting script (if desired).
  # - Runs Composer run-tests script.
  quick-tests:
    name: PHP ${{ matrix.php }} on PHPCS ${{ matrix.phpcs_branch }}${{ matrix.lint && ' with linting' || '' }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [ '7.4', '5.4' ]
        phpcs_branch: [ 'dev-master' ]
        include:
          - php: '7.3'
            phpcs_branch: '3.5.0'
          - php: '5.4'
            phpcs_branch: '3.5.0'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get Composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Set up Composer caching
        uses: actions/cache@v2
        env:
          cache-name: cache-composer-dependencies
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        if: ${{ matrix.phpcs_branch == 'dev-master' }}
        with:
          php-version: ${{ matrix.php }}

      # On stable PHPCS versions, allow for PHP deprecation notices.
      # Unit tests don't need to fail on those for stable releases where those issues won't get fixed anymore.
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        if: ${{ matrix.phpcs_branch != 'dev-master' }}
        with:
          php-version: ${{ matrix.php }}
          ini-values: error_reporting = E_ALL & ~E_DEPRECATED

      - name: Install PHPCS
        run: composer require squizlabs/php_codesniffer:"${{ matrix.phpcs_branch }}" --no-update --no-suggest --no-scripts

      - name: Install Composer dependencies
        run: composer install --no-suggest

      - name: Lint PHP files against parse errors
        if: ${{ matrix.phpcs_branch == 'dev-master' }}
        run: composer lint

      - name: Run unit tests
        run: composer run-tests
